USE MY_DATABASES;
SELECT * FROM BATH_TOWELS;
DELETE FROM BATH_TOWELS WHERE CODE ="821/9735";
DELETE FROM BATH_TOWELS WHERE CODE ="821/7355";
SELECT * FROM BATH_TOWELS;
DELETE FROM BATH_TOWELS;
SELECT * FROM BATH_TOWELS;
DROP TABLE TOWELS;
DROP TABLE BATH_TOWELS;