USE my_database;
SELECT * FROM BATH_TOWELS;
UPDATE BATH_TOWELS
SET COLOR = "BEIGE" WHERE NAME = "HARVEST";
UPDATE BATH_TOWELS
SET COLOR = "LILAC" WHERE NAME = "DOLPHIN";
UPDATE BATH_TOWELS
SET COLOR = "BLUE" WHERE NAME = "DAISY";
UPDATE BATH_TOWELS
SET NAME="TEMPEST",COLOR="MAROON"
WHERE CODE = "821/9628";
SELECT * FROM BATH_TOWELS;
